plugins:
  - jemoji
title: [Paris DVF&Co]
description: [Academic project at ENSAE about Paris real estate prediction]
show_downloads: true
remote_theme: tuur29/pages-themes-cayman
color:
  header: "#000"
  gradient_left: "#FADBD8"
  gradient_right: "#EB984E"

syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
buttons:
  zip_url: https://github.com/Orlogskapten/dvf_ensae_sbra
  zip_title: Voir le repository du projet
  zip_hide: false
  tar_hide: true
  github_hide: true
