theme: jekyll-theme-cayman
plugins:
  - jemoji

title: [Paris DVF&Co]
description: Academic project at ENSAE about Paris real estate prediction

darkmode: false
remote_theme: tuur29/pages-themes-cayman
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: https://stylishthemes.github.io/Syntax-Themes/pygments/css-github/pygments-monokai.css
colors:
    header: "#000"
    gradient_left: "#e53935"
    gradient_right: "#f57c00"

buttons:
  zip_url: https://github.com/Orlogskapten/dvf_ensae_sbra
  zip_title: [Voir le repository]
  zip_hide: false
  tar_hide: true
  github_hide: true
