theme: jekyll-theme-cayman
plugins:
  - jemoji

title: [Paris DVF&Co]
description: [Academic project at ENSAE about Paris real estate predictions]

darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    header: "#000"
    gradient_left: "#e53935"
    gradient_right: "#f57c00"
buttons:
      zip_url: http://example.com/
      zip_title: Title
      zip_hide: true
      tar_url: http://example.com/
      tar_title: Title
      tar_hide: true
      github_hide: true # hides "View on Github"
