theme: jekyll-theme-cayman
plugins:
  - jemoji

title: [Paris DVF&Co]
description: [Academic project at ENSAE about Paris real estate prediction A]

darkmode: false
hide_first_title: false # Useful if README.md is used on both github and pages
logo_url: ./logo.png # Either absolute or relative url
colors:
   # header: "#000"
    gradient_left: "#e53935"
    gradient_right: "#e6db74 "

buttons:
  zip_url: https://github.com/Orlogskapten/dvf_ensae_sbra
  zip_title: Voir le repository
  zip_hide: false
  tar_hide: true
  github_hide: true
