remote_theme: tuur29/pages-themes-cayman

plugins:
  - jemoji

title: [Paris DVF&Co]
description: [Academic project at ENSAE about Paris real estate prediction]

syntax_theme: ./syntax.css # Leave empty for default, otherwise link to a pygments stylesheet
colors:
    gradient_left: "#155799"
    gradient_right: "#159957"
    header: "#fff"
    android_theme: "#000" # this default to gradient_color
    link: "#1e6bb8" # this default to gradient_color
    section_title: "#155799" # this default to gradient_color
